### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by B-0-6** [markusaksli/ai-music#2]
I'm trying to train models based on my files, but I'm new to this. Sorry if this has been asked or told before. I've already tried using the train.py script and prepared my files and prerequisites as suggested, but I'm still having trouble. Can someone please provide more detailed guidance or clarify the process for me?

**Comment by markusaksli** [comment]
It's been a while since I've looked at this code but what problem are you running into?

**Comment by B-0-6** [comment]
1. I encounter this error:
    from music_transformer.convert import create_dataset, idxenc2stream, midi2idxenc
ModuleNotFoundError: No module named 'music_transformer'

Which was easy to solve by moving train.py to root directory.

2. Then:
     from transformer import *
ModuleNotFoundError: No module named 'transformer'

Which was resolved by correcting the typo from "transformer" to "transformers"

3. I had to install the backwards-compatible tf-keras package because of:
RuntimeError: Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

4. Am still encountering these things (related/unrelated to train.py):
4.a Even after installing, but I believe it was like ?2-3 times - After which it was resolved automatically.
  File "Python312\Lib\site-packages\transformers\activations_tf.py", line 22, in <module>
    import tf_keras as keras
ModuleNotFoundError: No module named 'tf_keras'

4.b
    transformer = TransformerDecoder(
                  ^^^^^^^^^^^^^^^^^^
NameError: name 'TransformerDecoder' is not defined

4.c I don't think this impacts the script much:
Python312\Lib\site-packages\transformers\deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
WARNING:tensorflow:From Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

PS: This is my first AI related project, which I dropped, so, I don't remember what else I did or did not do at the time. I had another query if this project supported some pre-trained models or not? If yes, where can I find them?

Thank you in advance!

**Comment by markusaksli** [comment]
The trained model is here:
https://github.com/markusaksli/ai-music/tree/main/trained_models/decoder_only_smaller_1024_mega_ds

Yeah strange that it would have this many issues, I remember subbing the last version of stuff in a working state but I haven't looked at this since writing it for uni. Newer python version or something. I was hoping it would kinda just work with https://github.com/markusaksli/ai-music/blob/main/setup.bat

2. That should be importing from `transformer.py` so not a typo, which should fix 4.b since it is defined here
https://github.com/markusaksli/ai-music/blob/7cc51e92410fcbfc0741130b2f56009fc9bcfa97/music_transformer/transformer.py#L201

Thank you for giving me this throwback though. So much has happened since I wrote this...

**Comment by B-0-6** [comment]
It's working now! Used Python 3.8 and 1 or 2 specific versions of a few modules (edit: wrote model instead module) as per StackOverflow.
As for the Models, I meant any other models besides the one already provided. Can Magenta 3.0 model be used for this? If yes, how can I use it?
You are welcome for the throwback and Thank you for telling it was transformer, and not transformers, which essentially solved most things.

**Comment by markusaksli** [comment]
Glad you got it working! As for other trained models I don't think so. The interface, sampling, search, etc were all very specific to this model.
